# Generated by Django 5.1.6 on 2025-03-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('members', models.ManyToManyField(blank=True, related_name='clubs_joined', to='schedules.student')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('rsvp_students', models.ManyToManyField(blank=True, related_name='events_rsvped', to='schedules.student')),
            ],
        ),
    ]
